version: '3.8'

services:
  n8n:
    image: busybox:latest
    container_name: n8n
    restart: unless-stopped
    command: ["tail", "-f", "/dev/null"]
    networks:
      - frontend
      - backend
  frps:
    image: busybox:latest
    container_name: frps
    ports:
      - "7000:7000"              # frp 客户端TCP连接端口，需要外部访问
      - "7000:7000/udp"          # KCP协议端口（UDP），直接暴露，不经过Nginx    restart: unless-stopped
    command: ["tail", "-f", "/dev/null"]
    networks:
      - frontend
      - backend
  ntfy:
    image: busybox:latest
    container_name: ntfy
    restart: unless-stopped
    command: ["tail", "-f", "/dev/null"]
    networks:
      - frontend
      - backend
  nginx-certbot:
    image: nginx-certbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-lib:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - nginx-logs:/var/log/nginx
    environment:
      - DOMAINS=www.example.com n8n.example.com ntfy.example.com frps.example.com # 替换为您的域名
      - EMAIL=admin@example.com # 替换为您的邮箱
      - STAGING=0 # 设置为1可使用Let's Encrypt的测试环境
      - MAIN_DOMAIN=www.example.com
      - N8N_DOMAIN=n8n.example.com
      - NTFY_DOMAIN=ntfy.example.com
      - FRPS_DOMAIN=frps.example.com
      - N8N_PORT=5678
      - NTFY_PORT=8080
      - FRPS_ADMIN_PORT=7500
      - FRPS_HTTP_PORT=8080
      - FRPS_HTTPS_PORT=8443
    restart: unless-stopped

volumes:
  certbot-conf:
  certbot-lib:
  certbot-www:
  nginx-logs:

networks:
  frontend:
    name: frontend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
  backend:
    name: backend
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16  # 后端网络地址段
