version: '3.8'

services:
  nginx-certbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-lib:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - nginx-logs:/var/log/nginx
    environment:
      - DOMAINS=www.example.com etc.example.com  # 替换为您的域名
      - EMAIL=admin@example.com              # 替换为您的邮箱
      - STAGING=0                            # 设置为1可使用Let's Encrypt的测试环境 
    restart: unless-stopped

volumes:
  certbot-conf:
  certbot-lib:
  certbot-www:
  nginx-logs:
